version: "1.0"
services:
    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: todo
        MYSQL_DATABASE: todo
        MYSQL_USER: todo
        MYSQL_PASSWORD: todo
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 5s
        timeout: 10s
        retries: 10
      ports:
        - 3306
      networks:
        - blink
    redis:
      image: redis
      # restart: always
      ports:
        - 6379
      networks:
        - blink
      command: redis-server --requirepass blinkable
    oss:
      image: minio/minio
      hostname: "minio"
      ports:
        - 9000:9000 # api 端口
        - 9001:9001 # 控制台端口
      environment:
        MINIO_ACCESS_KEY: todo
        MINIO_SECRET_KEY: todo
        MINIO_ROOT_USER: todo
        MINIO_ROOT_PASSWORD: todo
        # volumes:
        # - ./minio/data:/data
      command: server --console-address ':9001' /data
      privileged: true
      # restart: always
      networks:
        - blink

networks:
  blink:
    external: true